import LandingHeader from '../components/LandingHeader';
import { useTheme } from '../components/ThemeProvider';
import { useState } from 'react';

const mockPools = [
  {
    name: 'USDC Lending Pool',
    asset: 'USDC (Multi-chain)',
    chain: 'Multi-chain',
    apy: 5.3,
    collateralFactor: 0.75,
    tvl: 1200000,
    icon: '/logos/usd-coin-usdc-logo.png',
    status: 'Open',
    hover: 'USDC yield powered by cross-chain lending demand on Ethereum, Polygon, Base, and more.'
  },
  {
    name: 'ETH Lending Pool',
    asset: 'ETH',
    chain: 'Ethereum',
    apy: 3.8,
    collateralFactor: 0.80,
    tvl: 950000,
    icon: '/logos/ethereum-eth-logo.png',
    status: 'Open',
    hover: 'ETH yield comes from borrowers and DeFi activity on Ethereum and connected chains.'
  },
  {
    name: 'BNB Lending Pool',
    asset: 'BNB',
    chain: 'BNB Chain',
    apy: 6.1,
    collateralFactor: 0.70,
    tvl: 870000,
    icon: '/logos/bnb-bnb-logo.png',
    status: 'Open',
    hover: 'BNB yield is driven by lending demand and incentives on BNB Chain.'
  },
  {
    name: 'ZETA Staking Pool',
    asset: 'ZETA',
    chain: 'ZetaChain',
    apy: 7.1,
    collateralFactor: 0.75,
    tvl: 4300000,
    icon: '/logos/zetachain.png',
    status: 'Open',
    hover: 'ZETA staking rewards are powered by ZetaChain omnichain activity.'
  },
  {
    name: 'USDT Lending Pool',
    asset: 'USDT',
    chain: 'BNB Chain',
    apy: 4.5,
    collateralFactor: 0.82,
    tvl: 6200000,
    icon: '/logos/tether-usdt-logo.png',
    status: 'Open',
    hover: 'USDT yield comes from lending demand on BNB Chain and other supported networks.'
  },
  {
    name: 'MATIC Lending Pool',
    asset: 'MATIC',
    chain: 'Polygon',
    apy: 4.9,
    collateralFactor: 0.72,
    tvl: 540000,
    icon: '/logos/polygon-matic-logo.png',
    status: 'Open',
    hover: 'MATIC yield is generated by lending and DeFi activity on Polygon.'
  },
  {
    name: 'AVAX Lending Pool',
    asset: 'AVAX',
    chain: 'Avalanche',
    apy: 5.7,
    collateralFactor: 0.73,
    tvl: 410000,
    icon: '/logos/avalanche-avax-logo.png',
    status: 'Open',
    hover: 'AVAX yield is powered by lending and incentives on Avalanche.'
  },
  {
    name: 'ARB Lending Pool',
    asset: 'ARB',
    chain: 'Arbitrum',
    apy: 4.2,
    collateralFactor: 0.68,
    tvl: 320000,
    icon: '/logos/arbitrum-arb-logo.png',
    status: 'Open',
    hover: 'ARB yield comes from DeFi activity and incentives on Arbitrum.'
  },
  {
    name: 'BTC Lending Pool',
    asset: 'BTC',
    chain: 'Bitcoin',
    apy: 2.9,
    collateralFactor: 0.60,
    tvl: 1500000,
    icon: '/logos/bitcoin-btc-logo.png',
    status: 'Open',
    hover: 'BTC yield is powered by wrapped Bitcoin lending and cross-chain demand.'
  },
  {
    name: 'USDC Lending Pool',
    asset: 'USDC',
    chain: 'Base',
    apy: 5.0,
    collateralFactor: 0.78,
    tvl: 800000,
    icon: '/logos/usd-coin-usdc-logo.png',
    status: 'Open',
    hover: 'USDC yield on Base is driven by lending and DeFi activity on the Base network.'
  },
];

function formatUSD(num) {
  return '$' + num.toLocaleString();
}

function formatUSDShort(num) {
  if (num >= 1e9) return '$' + (num / 1e9).toFixed(1) + 'B';
  if (num >= 1e6) return '$' + (num / 1e6).toFixed(1) + 'M';
  if (num >= 1e3) return '$' + (num / 1e3).toFixed(1) + 'K';
  return '$' + num.toLocaleString();
}

function formatTokenAmount(num, symbol) {
  if (num >= 1e6) return (num / 1e6).toFixed(1) + 'M ' + symbol;
  if (num >= 1e3) return (num / 1e3).toFixed(1) + 'K ' + symbol;
  return num.toLocaleString() + ' ' + symbol;
}

export default function EarnPage() {
  const { theme } = useTheme();
  const [pools] = useState(mockPools);

  return (
    <>
      <LandingHeader brandClass="font-orbitron" />
      <main className="min-h-screen bg-[var(--background)] text-[var(--text-main)] pt-24 px-4">
        <div className="max-w-6xl mx-auto w-full">
          <h1 className="text-3xl md:text-4xl font-bold font-orbitron gradient-text mb-6">Earn Omnichain Yields Seamlessly</h1>
          <p className="text-[var(--text-muted)] mb-10">Supply your assets once and earn yields across multiple chains, powered by ZetaChain and OmniFuse vaults.</p>
          <div className="overflow-x-auto">
            <table className="min-w-full bg-[var(--card-bg)] rounded-2xl shadow-md border border-[#23272F]/10">
              <thead>
                <tr className="text-left text-sm text-[var(--text-muted)] border-b border-[#23272F]/10">
                  <th className="py-4 px-6">Asset</th>
                  <th className="py-4 px-6">Est. APY</th>
                  <th className="py-4 px-6">Collateral Factor</th>
                  <th className="py-4 px-6">TVL</th>
                  <th className="py-4 px-6">Action</th>
                </tr>
              </thead>
              <tbody>
                {pools.map((pool, idx) => (
                  <tr
                    key={idx}
                    className="group border-b border-[#23272F]/10 hover:bg-[var(--background)]/60 transition relative"
                  >
                    <td className="py-4 px-6 flex items-center gap-3">
                      <img src={pool.icon} alt={pool.asset} className="h-8 w-8 rounded-full bg-white/80 dark:bg-[#23272F] p-1" />
                      <span className="font-semibold">{pool.asset}</span>
                    </td>
                    <td className="py-4 px-6 font-bold text-green-500">{pool.apy}%</td>
                    <td className="py-4 px-6">{(pool.collateralFactor * 100).toFixed(0)}%</td>
                    <td className="py-4 px-6">
                      <div className="font-semibold">{formatUSDShort(pool.tvl)}</div>
                      <div className="text-xs text-[var(--text-muted)] mt-1">
                        {formatTokenAmount(pool.tvl / (pool.apy > 0 ? (1 + pool.apy / 100) : 1), pool.asset.split(' ')[0])}
                      </div>
                    </td>
                    <td className="py-4 px-6">
                      <button className="btn-primary px-5 py-2 rounded-lg font-semibold shadow-glow hover:scale-105 transition-transform">Deposit</button>
                    </td>
                    {/* Hover overlay/tooltip */}
                    <td className="absolute left-0 top-0 w-full h-full pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-200 z-10">
                      <div className="flex items-center justify-center h-full">
                        <div className="bg-[var(--card-bg)] border border-[#23272F]/20 shadow-lg rounded-xl px-6 py-3 text-sm text-[var(--text-main)] font-medium">
                          {pool.hover}
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
      {/* Info Cards Section */}
      <section className="max-w-6xl mx-auto w-full mt-12 grid grid-cols-1 md:grid-cols-3 gap-6 px-4">
        <div className="rounded-2xl bg-[var(--card-bg)] shadow-md border border-[#23272F]/10 p-6 flex flex-col items-center text-center">
          <div className="text-3xl mb-2">💸</div>
          <h3 className="font-bold text-lg mb-2">Passive Income</h3>
          <p className="text-[var(--text-muted)]">Earn yield on your assets by supplying liquidity or staking in secure, audited pools.</p>
        </div>
        <div className="rounded-2xl bg-[var(--card-bg)] shadow-md border border-[#23272F]/10 p-6 flex flex-col items-center text-center">
          <div className="text-3xl mb-2">🔒</div>
          <h3 className="font-bold text-lg mb-2">Non-Custodial</h3>
          <p className="text-[var(--text-muted)]">You remain in control of your funds at all times. Withdraw whenever you want, no lockups.</p>
        </div>
        <div className="rounded-2xl bg-[var(--card-bg)] shadow-md border border-[#23272F]/10 p-6 flex flex-col items-center text-center">
          <div className="text-3xl mb-2">🌐</div>
          <h3 className="font-bold text-lg mb-2">Omnichain Access</h3>
          <p className="text-[var(--text-muted)]">Supply and earn across multiple chains, maximizing your opportunities and rewards.</p>
        </div>
      </section>
      {/* FAQ Section */}
      <section className="max-w-3xl mx-auto w-full mt-16 mb-20 px-4">
        <h2 className="text-2xl font-bold font-orbitron mb-6 gradient-text">Frequently Asked Questions</h2>
        <div className="space-y-6">
          <div className="rounded-xl bg-[var(--card-bg)] border border-[#23272F]/10 p-5">
            <h4 className="font-semibold mb-2">How do I earn yield?</h4>
            <p className="text-[var(--text-muted)]">Deposit supported assets into any open pool. Your assets are used to provide liquidity or staking, and you earn a variable APY based on pool performance.</p>
          </div>
          <div className="rounded-xl bg-[var(--card-bg)] border border-[#23272F]/10 p-5">
            <h4 className="font-semibold mb-2">Are my funds safe?</h4>
            <p className="text-[var(--text-muted)]">All pools are non-custodial and smart contracts are audited. You can withdraw at any time. However, DeFi carries risks—always do your own research.</p>
          </div>
          <div className="rounded-xl bg-[var(--card-bg)] border border-[#23272F]/10 p-5">
            <h4 className="font-semibold mb-2">When can I withdraw?</h4>
            <p className="text-[var(--text-muted)]">You can withdraw your assets at any time, subject to pool liquidity. There are no lockup periods unless otherwise stated.</p>
          </div>
          <div className="rounded-xl bg-[var(--card-bg)] border border-[#23272F]/10 p-5">
            <h4 className="font-semibold mb-2">How is APY calculated?</h4>
            <p className="text-[var(--text-muted)]">APY is based on current pool performance and may fluctuate. Check each pool for the latest rates and details.</p>
          </div>
        </div>
      </section>
      {/* Yield Sources Explained (Education Block) */}
      <section className="max-w-3xl mx-auto w-full mb-20 px-4">
        <h2 className="text-2xl font-bold font-orbitron mb-4 gradient-text">Yield Sources Explained</h2>
        <div className="rounded-2xl bg-[var(--card-bg)] border border-[#23272F]/10 shadow-md p-6">
          <h4 className="font-semibold mb-3">Where does the yield come from?</h4>
          <ul className="list-disc pl-6 space-y-2 text-[var(--text-main)]">
            <li>Interest paid by borrowers across supported chains</li>
            <li>Platform incentives ($FUSE or similar)</li>
            <li>ZetaChain omnichain activity yield</li>
          </ul>
          <div className="flex items-center gap-2 mt-5 p-4 rounded-xl bg-[var(--background)]/80 border border-[#23272F]/10">
            <span className="text-2xl">🧠</span>
            <span className="text-[var(--text-muted)] font-medium">OmniFuse auto-routes your assets across chains to earn the highest return.</span>
          </div>
        </div>
      </section>
      {/* How to Start (Step Guide) */}
      <section className="max-w-3xl mx-auto w-full mb-20 px-4">
        <h2 className="text-2xl font-bold font-orbitron mb-4 gradient-text">How to Start</h2>
        <div className="rounded-2xl bg-[var(--card-bg)] border border-[#23272F]/10 shadow-md p-6 flex flex-col gap-6">
          <ol className="list-decimal pl-6 space-y-3 text-[var(--text-main)]">
            <li><span className="font-semibold">Connect Wallet</span> <span className="text-[var(--text-muted)]">(e.g., MetaMask, Zeta Wallet)</span></li>
            <li><span className="font-semibold">Choose an Asset & Vault</span></li>
            <li><span className="font-semibold">Supply and Start Earning</span></li>
          </ol>
          <button className="btn-primary mt-4 px-8 py-3 rounded-lg font-semibold shadow-glow text-lg self-center hover:scale-105 transition-transform">Connect Wallet</button>
        </div>
        {/* Optional Incentives and Rewards */}
        <div className="mt-10 rounded-2xl bg-[var(--card-bg)] border border-[#23272F]/10 shadow-md p-6">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xl">🔹</span>
            <span className="font-bold">6. Incentives and Rewards (Optional)</span>
          </div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xl">🎁</span>
            <span className="font-semibold">Boost Your Yield</span>
          </div>
          <ul className="list-disc pl-6 space-y-2 text-[var(--text-main)]">
            <li>Stake $FUSE to earn extra rewards</li>
            <li>Invite friends, earn referral bonuses</li>
          </ul>
        </div>
      </section>
    </>
  );
} 